blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^pc-geetest/ajax_validate', views.pcajax_validate, name='pcajax_validate'),
    url(r'^pc-geetest/register', views.pcgetcaptcha, name='pcgetcaptcha'),
    url(r'^index/', views.index),
    # url(r'^personal/',views.persional),
    url(r'^logout/', views.logout),
    url(r'^login_confirm/', views.login_confirm),
    url(r'^get_check_img/', views.get_check_img),
    url(r'^reg_check/', views.reg_check),
    url(r'^set_pwd/(?P<username>\w+)/$', views.set_pwd),

    # 博客首页网站分类查询
    url(r'^select/(?P<catename>\w+)/', views.select_catewebsite),

    # 点赞和取消
    url(r'^updown', views.up_down_ajax),
    # url(r'^(?P<username>\w+)/(?P<select_name>up|down)/(?P<keyword>\d+)/',views.up_down),

    # 文章评论
    url(r'^comment', views.comment),

    # 构建评论树
    url(r'^get/comment/tree/(?P<article_id>\d+)$', views.get_comment_tree),

    # 删除文章评论
    # url(r'^del/comment',views.del_comment),


    # 个人后台首页
    url(r'^manage/(?P<username>\w+)', views.manage),

    # 个人后台上传图片
    url(r'^upload_img', views.upload_img),

    #个人后台删除文章
    url(r'^del/article/(?P<keyword>\d+)',views.del_article),

    #个人后台编辑文章
    url(r'^edit/article/(?P<keyword>\d+)',views.edit_article),

    # 个人后台添加文章
    url(r'^(?P<username>\w+)/add/article', views.add_article),





    # 个人站点首页
    url(r'^(?P<username>\w+)/$', views.home_site),

    # 个人站点分类标签日期查询
    url(r'^(?P<username>\w+)/(?P<select_name>tag|cate|date)/(?P<keyword>.+)/', views.home_site),

    # 文章具体内容
    url(r'^(?P<username>\w+)/p/(?P<keyword>\d+)/', views.home_site_article),

]

version2/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.views.static import serve
from version2 import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index),
    url(r'^blog/',include("blog.urls")),
    url(r'^media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT})
]

blog/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser
class UserInfo(AbstractUser):
     """
     用户信息表
     实现登录和注册
     和个人站点是一对一的关系
     和推荐反对是一对多的关系
     和评论是一对多的关系
     """
     #用户名
     # username=models.CharField(max_length=50)
     # 密码
     # password=models.CharField(max_length=100)
     # 邮箱
     # email=models.EmailField(max_length=20)
     nid = models.AutoField(primary_key=True)
     #注册时间
     reg_time=models.DateField(verbose_name='创建时间', auto_now_add=True)
     #头像
     avatar = models.FileField(upload_to='user_head_picture/', default="user_head_picture/default.png")
     #电话
     telephone = models.CharField(max_length=11, null=True, unique=True)
     #昵称
     nickname = models.CharField(verbose_name='昵称', max_length=32)

     #和个人站点是一对一的关系
     user_blog=models.OneToOneField(to='Blog', to_field='nid',null=True,on_delete=None)

     def __str__(self):
         return self.username
class Blog(models.Model):
    """
    个人站点表
    和文章是一对多的关系
    和用户是一对一的关系
    和分类是一对多的关系
    和标签是一对多的关系
    """
    nid = models.AutoField(primary_key=True)
    #站点名称
    title = models.CharField(verbose_name = '个人博客标题', max_length = 64)
    #后缀
    site = models.CharField(verbose_name='个人博客后缀', max_length=32, unique=True)
    #博客主题
    theme = models.CharField(verbose_name='博客主题', max_length=32)
    #站点的形式
    style=models.CharField(max_length=50)
    def __str__(self):
        return self.title
class Article(models.Model):
    """
    文章表
    和个人站点是一对多的关系
    和用户是一对多的关系
    和分类是一对多的关系
    和标签是多对多的关系
    和推荐与反对是一对多的关系
    和评论是一对多的关系
    """
    nid = models.AutoField(primary_key=True)
    # 文章标题
    title=models.CharField(max_length=50, verbose_name='文章标题')
    # 文章创建时间
    create_time=models.DateTimeField(verbose_name='创建时间')
    # 文章摘要
    article_desc=models.CharField(max_length=255, verbose_name='文章描述')
    # 评论数
    comment_count = models.IntegerField(default=0)
    # 推荐数
    up_count = models.IntegerField(default=0)
    # 反对数
    down_count = models.IntegerField(default=0)

    # 和用户是一对多的关系，用户是一，文章是多
    article_user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid',on_delete=None)
    # 和分类是一对多的关系，分类是一，文章是多
    article_cate = models.ForeignKey(to='Cate', to_field='nid', null=True,on_delete=None)
    # 和标签是多对多的关系
    article_tags = models.ManyToManyField(
        to="Tag",
        through='Article_Tag',
        through_fields=('article', 'tag'),
    )
    # 和网站具体分类表是一对多的关系，具体分类是一，文章是多
    catewebsitedetail=models.ForeignKey(verbose_name='网站分类', to='CateWebsiteDetail', to_field='id',on_delete=None,null=True)
    # 和个人站点是一对多的关系，个人站点是一，文章是多,这一个老师的model没有写
    # article_blog=models.ForeignKey("Blog",on_delete=None)

    def __str__(self):
        return self.title


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()

    article = models.OneToOneField(to='Article', to_field='nid',on_delete=None)



class Cate(models.Model):
    """
    分类表
    和个人站点是一对多的关系
    和文章是一对多的关系
    """
    nid = models.AutoField(primary_key=True)
    # 分类名称
    cate_name=models.CharField(verbose_name='分类标题', max_length=32)
    # 对分类的描述
    cate_desc=models.CharField(max_length=50)

    # 和个人站点是一对多的关系，站点是一，分类是多
    cate_blog=models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid',on_delete=None)
    def __str__(self):
        return self.cate_name

class Tag(models.Model):
    """
    标签表
    和个人站点是一对多的关系
    和文章是多对多的关系
    """
    nid = models.AutoField(primary_key=True)
    # 标签名称
    tag_name=models.CharField(verbose_name='标签名称', max_length=32)
    # 标签描述
    tag_desc=models.CharField(max_length=50)

    # 和个人站点是一对多的关系，标签是多，个人站点是一
    tag_blog=models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid',on_delete=None)
    def __str__(self):
        return self.tag_name

class Article_Tag(models.Model):
    """
    文章和标签的关系表
    和文章是一对多的关系
    和标签是一对多的关系
    """
    nid = models.AutoField(primary_key=True)
    # 和文章是一对多的关系，文章是一
    article=models.ForeignKey(verbose_name='文章', to="Article", to_field='nid',on_delete=None)
    # 和标签是一对多的关系，标签是一
    tag=models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid',on_delete=None)
    #联合唯一
    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

class Articlepoll(models.Model):
    """
    文章推荐和反对表
    和用户是一对多的关系
    和文章是一对多的关系
    """
    nid = models.AutoField(primary_key=True)
    # 是推荐还是反对,true代表推荐，false代表反对
    is_agree=models.BooleanField(default=True)

    # 和用户是一对多的关系，用户是一
    user=models.ForeignKey("UserInfo",null=True,on_delete=None)
    # 和文章是一对多的关系，文章是一
    article=models.ForeignKey("Article",null=True,on_delete=None)
    #联合唯一
    class Meta:
        unique_together = [
            ('article', 'user'),
        ]

class Comment(models.Model):
    """
    评论表
    和用户是一对多的关系
    和文章是一对多的关系
    并且和自身做关联
    """
    nid = models.AutoField(primary_key=True)
    # 评论时间
    create_time=models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # 评论内容
    content=models.CharField(verbose_name='评论内容', max_length=255)

    # 和用户是一对多的关系
    user=models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid',on_delete=None)
    # 和文章是一对多的关系
    article=models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid',on_delete=None)
    # 属于哪条评论的评论，是文章的评论默认为None，和评论表做自关联
    parent_comment=models.ForeignKey('self', null=True,on_delete=None)


class CateWebsite(models.Model):
    """
    网站分类表
    和网站具体的分类是一对一的关系
    """
    name=models.CharField(verbose_name='分类名称', max_length=50)
    def __str__(self):
        return self.name
class CateWebsiteDetail(models.Model):
    """
    网站具体分类表
    和网站分类表是一对一的关系
    和文章表是一对多的关系
    """
    name=models.CharField(verbose_name='分类名称',max_length=50)
    #和文章分类表是一对一的关系
    catewebsite=models.ForeignKey("CateWebsite",on_delete=None)
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from blog.models import *
class Regform(forms.Form):
    whl=None
    # def __init__(self,request,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
    #     self.request=request
    username=forms.CharField(
        min_length=3,
        max_length=12,
        error_messages={
            "min_length":"用户名长度过短",
            "max_length":"用户名长度过长",
            "required":"用户名不能为空"
        },
        widget=widgets.TextInput(attrs={"class":"form-control","placeholder":"帐户名"})
    )
    password=forms.CharField(
        min_length=9,
        error_messages={
            "min_length":"密码长度过短",
            "required":"密码不能为空"
        },
        widget=widgets.PasswordInput(attrs={"class":"form-control","placeholder":"密码"})
    )
    repassword=forms.CharField(
        min_length=9,
        error_messages={
            "min_length":"密码长度过短",
            "required":"密码不能为空"
        },
        widget = widgets.PasswordInput(attrs={"class": "form-control","placeholder":"重新输入密码"})
    )
    email=forms.EmailField(
        error_messages={
            "required":"邮箱不能为空",
            "invalid":"邮箱格式错误"
        },
        widget=widgets.TextInput(attrs={"placeholder":"邮箱地址","class": "form-control"})
    )
    check_code=forms.CharField(
        error_messages={
            "required": "验证码不能为空",
        },
        widget=widgets.TextInput(attrs={"placeholder": "请输入右边图片中的验证码", "class": "form-control"})
    )
    # telphone=forms.IntegerField(
    #     max_value=11,
    #     min_value=11,
    #     error_messages={
    #         "required": "手机号不能为空",
    #         "invalid":"格式错误",
    #         "min_value":"手机号过短",
    #         "max_value":"手机号过长",
    #     },
    #     widget=widgets.TextInput(attrs={"placeholder": "手机号", "class": "form-control"})
    # )
    def clean_username(self):
        username = self.cleaned_data.get("username")
        user = UserInfo.objects.filter(username=username).first()
        if user:
            raise ValidationError("该用户已存在")
        else:
            return self.cleaned_data.get("username")
    def clean_password(self):
        if self.cleaned_data.get("password").isdigit():
            raise ValidationError("密码不能为纯数字")
        elif self.cleaned_data.get("password").isalpha():
            raise ValidationError("密码不能为纯字母")
        else:
            return self.cleaned_data.get("password")
    def clean_check_code(self):
        if self.cleaned_data.get("check_code").upper()==self.whl.upper():
            return self.cleaned_data.get("check_code")
        else:
            raise ValidationError("验证码输入不正确")
    def clean(self):
        if self.cleaned_data.get("password"):
            if self.cleaned_data.get("password") == self.cleaned_data.get("repassword"):
                return self.cleaned_data
            else:
                raise ValidationError("密码输入不一致")
        else:
            return self.cleaned_data

templates/first_page.html
<!DOCTYPE html>
<!-- saved from url=(0041)http://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/imgs/icon.ico">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <link href="/static/Dashboard-Template/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/Dashboard-Template/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/Dashboard-Template/dashboard.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/whl.css">
    <title>博客园</title>
</head>
<body>
{#导航条#}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/blog/index">博客园</a>
            <a class="navbar-brand t1" href="">随笔</a>
            <a class="navbar-brand t" href="">园子</a>
            <a class="navbar-brand t" href="">新闻</a>
            <a class="navbar-brand t" href="">博问</a>
            <a class="navbar-brand t" href="">小组</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="/blog/{{ request.user.username }}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>{{ request.user.username }}
                    </a></li>
                    <li><a style="font-size: 12px" href="/blog/set_pwd/{{ request.user.username }}">修改密码</a>
                    </li>
                    <li><a style="font-size: 12px" href="/blog/logout">注销</a></li>
                {% else %}
                    <li><a style="font-size: 12px" href="/blog/login_confirm/">登录</a></li>
                    <li><a style="font-size: 12px" href="/blog/reg_check">注册</a></li>
                {% endif %}
                <li class="dropdown">
                    <a style="font-size: 12px" class="dropdown-toggle" data-toggle="dropdown"
                       role="button" aria-haspopup="true" aria-expanded="true">设置 <span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid" style="margin-top: 20px">
    <div class="row">
        <div class="col-lg-2">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="panel-title">网站分类</h4>
                </div>
                <div class="panel-body">
                    {#                    {% for catewebsite in cate_list %}#}
                    {#                        <div class="cate">{{ catewebsite.name }}</div>#}
                    {#                        <ul class="catedetail hide">#}
                    {#                            {% for item in catewebsite.catewebsitedetail_set.all %}#}
                    {#                                <li class="catedetail"><a href="">{{ item.name }}</a></li>#}
                    {#                            {% endfor %}#}
                    {#                        </ul>#}
                    {#                    {% endfor %}#}
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        {% for catewebsite in catewebsite_list %}
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="{{ catewebsite.id }}">
                                    <h4 class="panel-title">
                                        <a style="font-size: 15px" role="button" data-toggle="collapse" data-parent="#accordion"
                                           href="#{{ catewebsite.name }}"
                                           aria-expanded="false" aria-controls="{{ catewebsite.name }}">
                                            {{ catewebsite.name }}
                                        </a>
                                    </h4>
                                </div>
                                <div id="{{ catewebsite.name }}" class="panel-collapse collapse" role="tabpanel"
                                     aria-labelledby="{{ catewebsite.id }}">
                                    <div class="panel-body">
                                        <div>
                                            {% for item in catewebsite.catewebsitedetail_set.all %}
                                                <div style="text-align:left ;"><a
                                                        href="/blog/select/{{ item.name }}">{{ item.name }}</a>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {#                    {% for catewebsite in cate_list %}#}
                    {#                        <div class="panel panel-info">#}
                    {#                            <div class="panel-heading">#}
                    {#                                <h3  class="panel-title">{{ catewebsite.name }}</h3>#}
                    {#                            </div>#}
                    {#                            <div class="panel-body" style="display: none">#}
                    {#                                {% for item in catewebsite.catewebsitedetail_set.all %}#}
                    {#                                    <div class="catedetail">{{ item.name }}</div>#}
                    {#                                {% endfor %}#}
                    {#                            </div>#}
                    {#                        </div>#}
                    {#                    {% endfor %}#}
                </div>
            </div>
        </div>
        <div class="col-lg-7">
            {% for article in article_list %}
                <div id="article_title"><h4><strong><a href="/blog/{{ article.article_user }}/p/{{ article.nid }}">{{ article.title }}</a></strong></h4></div>
                <div class="row">
                    <div class="col-md-1">
                        <a href="/blog/{{ article.article_user.username }}/"><img class="user_img" src="/media/{{ article.article_user.avatar }}" alt=""
                                        width="60px" height="60px"></a>
                    </div>
                    <div class="col-md-10 article_desc">
                        <span>{{ article.article_desc }}</span>
                    </div>
                </div>
                <div class="info">
                    <a href="/blog/{{ article.article_user.username }}/">{{ article.article_user.username }}</a>&nbsp;&nbsp;
                    <span class="article_time">发布于 {{ article.create_time|date:"Y-m-d H:i" }}</span>&nbsp;&nbsp;
                    <span class="glyphicon glyphicon-comment" style="margin-top: 3px"></span>
                    <span>
                    <a id="conment" href="">评论({{ article.comment_count }})</a>
                </span>&nbsp;&nbsp;
                    <span class="glyphicon glyphicon-thumbs-up" style="margin-top: 5px"></span>
                    <span>
                    <a class="up" href="">推荐({{ article.up_count }})</a>
                </span>
                </div>
                <hr>
            {% endfor %}
        </div>
        <div class="col-lg-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4 class="panel-title">Panel title</h4>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4 class="panel-title">Panel title</h4>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h4 class="panel-title">Panel title</h4>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/static/Dashboard-Template/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="/static/Dashboard-Template/bootstrap.min.js"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="/static/Dashboard-Template/holder.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/static/Dashboard-Template/ie10-viewport-bug-workaround.js"></script>
{#    <script src="/static/bootstrap-3.3.7/js/bootstarp.js/bootstrap.min.js"></script>#}
<script src="/static/js/first-page-js.js"></script>
</body>
</html>

templates/reg_check.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>注册</title>
    <link rel="icon" href="/static/imgs/icon.ico">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/whll.css">
    <link rel="stylesheet" href="/static/css/reg_check.css">
    <!-- 为使用方便，直接使用jquery.js库，如您代码中不需要，可以去掉 -->
    <script src="http://code.jquery.com/jquery-1.12.3.min.js"></script>
    <!-- 引入封装了failback的接口--initGeetest -->
    <script src="http://static.geetest.com/static/tools/gt.js"></script>
</head>
<body>
<div class="container" style="margin-top: 100px;margin-left: 150px">
    <div class="row">
        <div class=""><h3 class="text-center">Ajax注册+form组件校验</h3></div>
    </div>
    <form class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username" class="col-sm-3 control-label">用户名</label>
            <div class="col-sm-6">
                {{ reg_form.username }}
                {#                <input name="username" type="text" class="form-control"  >#}
                <span class="error" style="color:red;font-size: 12px"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="id_password" class="col-sm-3 control-label">密码</label>
            <div class="col-sm-6">
                {{ reg_form.password }}
                {#                <input name="pwd"  type="password" class="form-control"  >#}
                <span class="error" style="color:red;font-size: 12px"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="id_repassword" class="col-sm-3 control-label">请确认密码</label>
            <div class="col-sm-6">
                {{ reg_form.repassword }}
                {#                <input name="newpwd"  type="password" class="form-control">#}
                <span class="error" style="color:red;font-size: 12px"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="id_email" class="col-sm-3 control-label">邮箱</label>
            <div class="col-sm-6">
                {{ reg_form.email }}
                {#                <input name="cemail"  type="email" class="form-control" >#}
                <span class="error" style="color:red;font-size: 12px"></span>
            </div>
        </div>
{#        <div class="form-group">#}
{#            <label for="id_telphone" class="col-sm-3 control-label">手机号</label>#}
{#            <div class="col-sm-6">#}
{#                {{ reg_form.telphone }}#}
                {#                <input name="cemail"  type="email" class="form-control" >#}
{#                <span class="error" style="color:red;font-size: 12px"></span>#}
{#            </div>#}
{#        </div>#}
        <div class="form-group box">
            <label for="file" class="col-sm-3 control-label">头像</label>
            <div class="col-sm-6 father">
                <img src="/static/imgs/default.png" alt="" class="img">
                <input type="file" class="form-control" id="file">
            </div>
        </div>
        <div class="form-group">
            <label for="id_check_code" class="col-sm-3 control-label">验证码</label>
            <div class="col-sm-3">
                {#                <input type="text" class="form-control" id="check_code" placeholder="请输入右边图片中的验证码">#}
                {{ reg_form.check_code }}
                <span class="error" style="color:red;font-size: 12px"></span>
            </div>
            <div class="col-sm-3">
                <img class="pull-right" src="/blog/get_check_img/" width="260" height="40" id="check_img">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <input type="button" class="btn btn-primary btn-block sub" id="popup-submit" value="提交">
            </div>
        </div>
{#    </form>#}
{#    <div class="popup" style="display: none">#}
{#        <h2>弹出式Demo，使用ajax形式提交二次验证码所需的验证结果值</h2>#}
{#        <labe>用户名：</labe>#}
{#        <input id="username1" class="inp" type="text" value="极验验证">#}
{#        <label>密&nbsp;&nbsp;&nbsp;&nbsp;码：</label>#}
{#        <input id="password1" class="inp" type="password" value="123456">#}
{#        <input class="btn" id="popup-submit" type="submit" value="提交">#}
{##}
{#        <div id="popup-captcha"></div>#}
{#    </div>#}
</div>
<script src="/static/js/jquery-3.2.1.min.js"></script>
<script src="/static/js/jquery.cookie.js"></script>
<script src="/static/js/reg_blog_check.js"></script>
</body>
</html>

templates/setpwd.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="icon" href="/static/imgs/icon.ico">
    <title>修改密码</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/whll.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class=""><h3 class="text-center">修改密码</h3></div>
    </div>
    <form action="/blog/set_pwd/{{ username }}/" method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="username" class="col-sm-5 control-label">用户名</label>
            <div class="col-sm-3">
                <input name="username" value="{{ username }}" type="text" class="form-control" id="username" placeholder="帐户名">
            </div>
        </div>
        <div class="form-group">
            <label for="id_oldpassword" class="col-sm-5 control-label">原密码</label>
            <div class="col-sm-3">
                <input name="oldpwd"  type="password" class="form-control" id="id_oldpassword" placeholder="原密码">
                <span class="error" style="color:red;font-size: 12px">{{ errors_msg_oldpwd }}</span>
            </div>
        </div>
        <div class="form-group">
            <label for="id_password" class="col-sm-5 control-label">新密码</label>
            <div class="col-sm-3">
                <input name="newpwd"  type="password" class="form-control" id="" placeholder="密码">
{#                {{ setform.password }}#}
                <span class="error" style="color:red;font-size: 12px">{{ errors_msg_newpwd }}</span>
            </div>
        </div>
        <div class="form-group">
            <label for="id_repassword" class="col-sm-5 control-label">确认密码</label>
            <div class="col-sm-3">
                <input name="repeatpwd"  type="password" class="form-control" id="" placeholder="密码">
{#                {{ setform.repassword }}#}
                <span class="error" style="color:red;font-size: 12px">{{ errors_msg_repeatpwd }}</span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-5 col-sm-3">
                <button type="submit" class="btn btn-primary btn-block">提交</button>
            </div>
        </div>

    </form>
</div>
</body>
</html>